// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6RR3IiBSA3TaotRBARsjrvAAbsnpis4',
    appId: '1:476787087429:web:c429b24d629cec55d76b2c',
    messagingSenderId: '476787087429',
    projectId: 'report4-93478',
    authDomain: 'report4-93478.firebaseapp.com',
    storageBucket: 'report4-93478.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAueLIFP9seWHyPBEmFFhqIZAuSTesXoe8',
    appId: '1:476787087429:android:ccb60447b70e926bd76b2c',
    messagingSenderId: '476787087429',
    projectId: 'report4-93478',
    storageBucket: 'report4-93478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYN8Q_mBFT-e9CKRXCTEDpeAPqxxtHrZg',
    appId: '1:476787087429:ios:8438f3ecfec610bdd76b2c',
    messagingSenderId: '476787087429',
    projectId: 'report4-93478',
    storageBucket: 'report4-93478.appspot.com',
    iosClientId: '476787087429-htjbc8ii374skv30kh8dv2aa6g96mvia.apps.googleusercontent.com',
    iosBundleId: 'com.example.report4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYN8Q_mBFT-e9CKRXCTEDpeAPqxxtHrZg',
    appId: '1:476787087429:ios:8438f3ecfec610bdd76b2c',
    messagingSenderId: '476787087429',
    projectId: 'report4-93478',
    storageBucket: 'report4-93478.appspot.com',
    iosClientId: '476787087429-htjbc8ii374skv30kh8dv2aa6g96mvia.apps.googleusercontent.com',
    iosBundleId: 'com.example.report4',
  );
}
